name: Publish Chrison .NET Validators on NuGet
 
on:
  push:
    paths: ['Chrison.Validators/**', '.github/workflows/Chrison.Validators-Nuget-Package.yml']
  pull_request:
    paths: ['Chrison.Validators/**']
  workflow_dispatch:

env:
  NET_VERSION: '9.x'
  PROJECT_NAME: Chrison.Validators
  PROJECT_FILE: Chrison.Validators.csproj
  RELEASE_NAME: Chrison.Validators
  
jobs:
  publish:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Add permissions to create a github release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'
        
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}
        
    - name: Package
      run: dotnet pack -c Release -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'
      
    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json  
      
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          tag_name: v${{ steps.nbgv.outputs.NuGetPackageVersion }}
          release_name: ${{ env.RELEASE_NAME }} ${{ steps.nbgv.outputs.NuGetPackageVersion }}
          draft: false
          prerelease: false
