name: Code Coverage Chrison.Validators

on:
  push:
    branches: [ master ]
    paths: [ 'Chrison.Validators/**' ]
  workflow_dispatch:

env:
  NET_VERSION: '9.x'
  RELEASE_CONFIG: Release
  PROJECT_NAME: Chrison.Validators

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage" #-p:CollectCoverage=true -p:CoverletOutputFormat=opencover

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: '**/TestResults/**/coverage.cobertura.xml'